# Hey there XRPL fan!

[METADATA]
modified = 2022-05-25T09:29:00

[[ACCOUNTS]]
address = "rV3WAvwwXgvPrYiUgSoytn9w3mejtPgLo"
desc = "Want to tip me in XRP? Do it here!"

[[PRINCIPALS]]
name = "Greg Weisbrod"
email = "greg.weisbrod@gmail.com"
