# Hey there XRPL fan!

[METADATA]
modified = 2023-05-06T00:27:00

[[ACCOUNTS]]
address = "rV3WAvwwXgvPrYiUgSoytn9w3mejtPgLo"
desc = "Want to tip me in XRP? Do it here!"

[[PRINCIPALS]]
name = "Greg Weisbrod"
