name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Display node version
        run: node -v
      - name: Display npm version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREGWEISBRODSITE }}'
          channelId: live
          projectId: gregweisbrodsite
