name: Lint

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint
