name: Lint

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Display node version
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
